### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [cmpsc100-allegheny-college/datamart#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reporting back

- [ ] No TODO markers left in any individual reflection
- [ ] No TODO markers left in the group report

## Make the report

- [ ] No TODO markers left in analyzer&#x2F;main.py

## Function Junction

- [ ] Implements correct function signature for get_row
- [ ] Implements correct function signature for get_col
- [ ] Implements correct function signature for counter
- [ ] Implements correct function signature for min_value
- [ ] Implements correct function signature for max_value
- [ ] Implements correct function signature for avg_column
- [ ] Implements correct function signature for get_mode
- [ ] Implements correct function signature for get_median
- [ ] Makes correct function call to get_row
- [ ] Makes correct function call to counter
- [ ] Makes correct function call to min_value
- [ ] Makes correct function call to max_value
- [ ] Makes correct function call to max_value
- [ ] Makes correct function call to avg_column
- [ ] Makes correct function call to get_mode
- [ ] Makes correct function call to get_median
- [ ] Makes correct function call to get_col

## Data Dive

- [ ] Uses for loops in functions to iterate through ROWS
- [x] Uses a for loop to determine the mode (not using ROWS)
- [ ] Code retrieves specific indexes of lists using [] (i.e. COLS\[idx])
- [x] Code retrieves index of list using .index method
- [ ] Code uses the len() built-in function to get list length

## Percent complete

Based on the checks achieved, this assignment is `8%` complete.
